export default [
  { id: 1, name: 'あ', text: 'アリドリア', src: '/img/01_a.png' },
  { id: 2, name: 'い', text: '犬理科で仮縫い', src: '/img/02_i.png' },
  { id: 3, name: 'う', text: '占い習う', src: '/img/03_u.png' },
  { id: 4, name: 'え', text: '笑みなくなり泣く奈美恵', src: '/img/04_e.png' },
  { id: 5, name: 'お', text: '折り曲げマリオ', src: '/img/05_o.jpg' },
  { id: 6, name: 'か', text: 'カツラが落下', src: '/img/06_ka_01.png' },
  { id: 7, name: 'が', text: 'ガイコツ初恋が', src: '/img/07_ka_02.jpg' },
  {
    id: 8,
    name: 'き',
    text: '喫茶店建てたんてさっき？',
    src: '/img/08_ki.png',
  },
  { id: 9, name: 'く', text: '口から家畜', src: '/img/09_ku.png' },
  {
    id: 10,
    name: 'け',
    text: 'ケツを木につけ、ケツに気をつけ',
    src: '/img/10_ke.png',
  },
  { id: 11, name: 'こ', text: '腰なし子', src: '/img/11_ko.png' },
  { id: 12, name: 'さ', text: '参観日も敏感さ', src: '/img/12_sa.jpg' },
  // { id: 13, name: 'さ', text: '参観日も敏感さ', src: '/img/13_sa_02.jpg' },
  { id: 14, name: 'し', text: '死にたいタニシ', src: '/img/14_si.png' },
  { id: 15, name: 'す', text: 'スマートなトーマス', src: '/img/15_su.png' },
  { id: 16, name: 'せ', text: 'セミいない階無い店', src: '/img/16_se.jpg' },
  {
    id: 17,
    name: 'そ',
    text: 'ソクラテスら暮らす寺クソ',
    src: '/img/17_so.png',
  },
  { id: 18, name: 'た', text: '竜田揚げ当たった', src: '/img/18_ta.png' },
  {
    id: 19,
    name: 'ち',
    text: 'チンパンジー離岸 ハンガリー人パンチ',
    src: '/img/19_ti.png',
  },
  { id: 20, name: 'つ', text: 'つまんねぇ年末', src: '/img/20_tu.png' },
  { id: 21, name: 'て', text: '鉄火丼買って！', src: '/img/21_te.png' },
  { id: 22, name: 'と', text: '賭博ハト', src: '/img/22_to.png' },
  { id: 23, name: 'な', text: '名倉揺らぐな', src: '/img/23_na.png' },
  { id: 24, name: 'に', text: '妊娠線全身に', src: '/img/24_ni.png' },
  { id: 25, name: 'ぬ', text: '縫い込んだん？子犬', src: '/img/25_nu.jpg' },
  { id: 26, name: 'ね', text: '値段盛り、尻揉んだね？', src: '/img/26_ne.jpg' },
  { id: 27, name: 'の', text: '呑気でもできんの？', src: '/img/27_no.jpg' },
  { id: 28, name: 'は', text: 'ハゲ頭にまたアゲハ', src: '/img/28_ha.png' },
  { id: 29, name: 'ひ', text: '昼か！？膝光る日', src: '/img/29_hi.png' },
  { id: 30, name: 'ふ', text: '震えるプルプルエルフ', src: '/img/30_hu.png' },
  { id: 31, name: 'へ', text: 'ヘルでも出る屁', src: '/img/31_he.png' },
  { id: 32, name: 'ほ', text: '包帯巻いたウホ♡', src: '/img/32_ho_01.png' },
  {
    id: 33,
    name: 'ほ',
    text: '方向音痴ん家のちんちん王候補',
    src: '/img/33_ho_02.jpg',
  },
  { id: 34, name: 'ま', text: '舞茸・酒・大麻', src: '/img/34_ma.png' },
  { id: 35, name: 'み', text: '水着脱ぎ済み', src: '/img/35_mi.png' },
  { id: 36, name: 'む', text: 'ムカついて布袋掴む', src: '/img/36_mu.png' },
  { id: 37, name: 'め', text: 'メグロ締め', src: '/img/37_me.png' },
  { id: 38, name: 'も', text: '喪服踏も', src: '/img/38_mo.png' },
  // { id: 39, name: 'や', text: '', src: '/img/39_ya_01.jpg' },
  { id: 40, name: 'や', text: 'やずややずや', src: '/img/40_ya_02.jpg' },
  { id: 41, name: 'ゆ', text: 'ゆず湯', src: '/img/41_yu.png' },
  { id: 42, name: 'よ', text: '夜うるさい猿売るよ', src: '/img/42_yo_01.jpg' },
  {
    id: 43,
    name: 'よ',
    text: '洋子行くガン検診見学行こうよ',
    src: '/img/43_yo_02.jpg',
  },
  { id: 44, name: 'ら', text: 'ラブ手ぶら♡', src: '/img/44_ra_01.jpg' },
  // { id: 45, name: 'ら', text: 'ラブ手ぶら♡', src: '/img/45_ra_02.jpg' },
  { id: 46, name: 'り', text: 'リス似の殿にスリ', src: '/img/46_ri.png' },
  { id: 47, name: 'る', text: '塁審、点強いる', src: '/img/47_ru_01.jpg' },
  {
    id: 48,
    name: 'る',
    text: 'ルイージ萎えるエナジー、いる？',
    src: '/img/48_ru_02.jpg',
  },
  { id: 49, name: 'れ', text: 'レズバーのあばずれ', src: '/img/49_re.jpg' },
  { id: 50, name: 'ろ', text: '６ドクロ', src: '/img/50_.jpg' },
  { id: 51, name: 'わ', text: '我が庭にワニ革', src: '/img/51_wa.png' },
  { id: 52, name: 'を', text: '叔母さん鯖を・・・', src: '/img/52_wo.jpg' },
  { id: 53, name: 'ん', text: 'んー、象舞うゾーン！', src: '/img/53_nn.png' },
]
